# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rob.challen@bristol.ac.uk
# R wrapper for OpenHTMLtoPDF java library
#' R6 Bindings for Java HtmlConverter
#'
#' @description
#' missing description
#' 
#' This is a class of the html2pdfr generated R library.
#' 
#' Version: 0.01
#' 
#' Generated: 2022-02-15T20:55:56.413
#'
#' @details
	#' no details
#' @export
HtmlConverter = R6::R6Class("HtmlConverter", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new HtmlConverter this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new HtmlConverter object.
	#' @examples
	#' J = html2pdfr::JavaApi$get();
	#' instance = J$HtmlConverter$new(fontfiles=  "extrafont::fonttable()$fontfile)
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' urlToPdf: 
	#' no description
	#' @param htmlUrl - (java expects a String)
	#' @param outFile - (java expects a String)
	#' @return RCharacter: 
	#' 
	urlToPdf = function(htmlUrl, outFile) {
		# copy parameters
		tmp_htmlUrl = self$.api$.toJava$String(htmlUrl);
		tmp_outFile = self$.api$.toJava$String(outFile);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="urlToPdf" , tmp_htmlUrl, tmp_outFile); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' fileToPdf: 
	#' no description
	#' @param inFile - (java expects a String)
	#' @param outFile - (java expects a String)
	#' @return RCharacter: 
	#' 
	fileToPdf = function(inFile, outFile) {
		# copy parameters
		tmp_inFile = self$.api$.toJava$String(inFile);
		tmp_outFile = self$.api$.toJava$String(outFile);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="fileToPdf" , tmp_inFile, tmp_outFile); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' stringToPdf: 
	#' no description
	#' @param html - (java expects a String)
	#' @param outFile - (java expects a String)
	#' @param baseUri - (java expects a RCharacter)
	#' @return RCharacter: 
	#' 
	stringToPdf = function(html, outFile, baseUri=NA_character_) {
		# copy parameters
		tmp_html = self$.api$.toJava$String(html);
		tmp_outFile = self$.api$.toJava$String(outFile);
		tmp_baseUri = self$.api$.toJava$RCharacter(baseUri);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="stringToPdf" , tmp_html, tmp_outFile, tmp_baseUri); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' fitIntoPage: 
	#' no description
	#' @param htmlFragment - (java expects a String)
	#' @param outFile - (java expects a String)
	#' @param maxWidthInches - (java expects a double)
	#' @param maxHeightInches - (java expects a double)
	#' @param formats - (java expects a String)
	#' @param pngDpi - (java expects a double)
	#' @return RCharacterVector: 
	#' 
	fitIntoPage = function(htmlFragment, outFile, maxWidthInches=6.25, maxHeightInches=9.75, formats=c('pdf','png'), pngDpi=300) {
		# copy parameters
		tmp_htmlFragment = self$.api$.toJava$String(htmlFragment);
		tmp_outFile = self$.api$.toJava$String(outFile);
		tmp_maxWidthInches = self$.api$.toJava$double(maxWidthInches);
		tmp_maxHeightInches = self$.api$.toJava$double(maxHeightInches);
		tmp_formats = self$.api$.toJava$String(formats);
		tmp_pngDpi = self$.api$.toJava$double(pngDpi);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacterVector;", method="fitIntoPage" , tmp_htmlFragment, tmp_outFile, tmp_maxWidthInches, tmp_maxHeightInches, tmp_formats, tmp_pngDpi); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacterVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' fitIntoA4: 
	#' no description
	#' @param htmlFragment - (java expects a String)
	#' @param outFile - (java expects a String)
	#' @param xMarginInInches - (java expects a double)
	#' @param yMarginInInches - (java expects a double)
	#' @return RCharacterVector: 
	#' 
	fitIntoA4 = function(htmlFragment, outFile, xMarginInInches=1.0, yMarginInInches=1.0) {
		# copy parameters
		tmp_htmlFragment = self$.api$.toJava$String(htmlFragment);
		tmp_outFile = self$.api$.toJava$String(outFile);
		tmp_xMarginInInches = self$.api$.toJava$double(xMarginInInches);
		tmp_yMarginInInches = self$.api$.toJava$double(yMarginInInches);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacterVector;", method="fitIntoA4" , tmp_htmlFragment, tmp_outFile, tmp_xMarginInInches, tmp_yMarginInInches); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacterVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	#' @description The output of toString() of this HtmlConverter
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this HtmlConverter
	#' @param object The R6 instance to test for equality to this HtmlConverter  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		try(.jcall(self$.jobj, returnSig = "V", method="close"))
		self$.jobj = .jnull("uk/co/terminological/html2pdfr/HtmlConverter")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
