# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob.challen@bristol.ac.uk
# Automated tests for R Wrapper For Openhtmltopdf Java Library}

library(testthat)
library(html2pdfr)

test_check("html2pdfr")