# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rob.challen@bristol.ac.uk
# R wrapper for OpenHTMLtoPDF java library
#' R6 Bindings for Java HtmlConverter
#'
#' @description
#' missing description
#' 
#' This is a class of the html2pdfr generated R library.
#' 
#' Version: 0.1.0
#' 
#' Generated: 2022-06-17T23:54:57.038
#'
#' @details
	#' no details
#' @export
HtmlConverter = R6::R6Class("HtmlConverter", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new HtmlConverter this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new HtmlConverter object.
	#' @examples
	#' J = html2pdfr::JavaApi$get();
	#' instance = J$HtmlConverter$new(fontfiles=extrafont::fonttable()$fontfile)
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' urlToPdf: 
	#' Convert HTML from a URL to a PDF file. PDF size will be controlled by page media directives within the html.
	#' @param htmlUrl the URL - (java expects a String)
	#' @param outFile the full path of the output file - (java expects a String)
	#' @return RCharacter: 
	#' the filename written to (with extension '.pdf' if outFile did not have an extension).
	urlToPdf = function(htmlUrl, outFile) {
		# copy parameters
		tmp_htmlUrl = self$.api$.toJava$String(htmlUrl);
		tmp_outFile = self$.api$.toJava$String(outFile);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="urlToPdf" , tmp_htmlUrl, tmp_outFile, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' urlComponentToPdf: 
	#' Convert HTML from a URL to a PDF file. PDF size will be controlled by page media directives within the html.
	#' @param htmlUrl the URL - (java expects a String)
	#' @param outFile the full path of the output file - (java expects a String)
	#' @param cssSelector the part of the page you want to convert to PDF. - (java expects a String)
	#' @return RCharacter: 
	#' the filename written to (with extension '.pdf' if outFile did not have an extension).
	urlComponentToPdf = function(htmlUrl, outFile, cssSelector) {
		# copy parameters
		tmp_htmlUrl = self$.api$.toJava$String(htmlUrl);
		tmp_outFile = self$.api$.toJava$String(outFile);
		tmp_cssSelector = self$.api$.toJava$String(cssSelector);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="urlComponentToPdf" , tmp_htmlUrl, tmp_outFile, tmp_cssSelector, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' fileToPdf: 
	#' Convert HTML from a local file to a PDF file. PDF size will be controlled by page media directives within the html.
	#' @param inFile the full path to an input HTML file - (java expects a String)
	#' @param outFile the full path to the output pdf file. (N.B. this function can also output PNG if specified in the filename extension) - (java expects a String)
	#' @return RCharacter: 
	#' the filename written to (with extension '.pdf' if outFile did not have an extension).
	fileToPdf = function(inFile, outFile) {
		# copy parameters
		tmp_inFile = self$.api$.toJava$String(inFile);
		tmp_outFile = self$.api$.toJava$String(outFile);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="fileToPdf" , tmp_inFile, tmp_outFile, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' stringToPdf: 
	#' no description
	#' @param html the HTML string - (java expects a String)
	#' @param outFile the full path to the output pdf file (N.B. this function can also output PNG if specified in the filename extension) - (java expects a String)
	#' @param baseUri optionally the base URI of the HTML string for resolving relative URLs in the HTML (e.g. CSS files). - (defaulting to NA_character_) - (java expects a RCharacter)
	#' @return RCharacter: 
	#' the filename written to (with extension '.pdf' if outFile did not have an extension).
	stringToPdf = function(html, outFile, baseUri=NA_character_) {
		# copy parameters
		tmp_html = self$.api$.toJava$String(html);
		tmp_outFile = self$.api$.toJava$String(outFile);
		tmp_baseUri = self$.api$.toJava$RCharacter(baseUri);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="stringToPdf" , tmp_html, tmp_outFile, tmp_baseUri, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' fitIntoPage: 
	#' Render HTML string to fit into a page,
	#' @param htmlFragment a HTML fragment, e.g. the table element. It is usually expected there will not be any page media directives in the HTML - (java expects a String)
	#' @param outFile the full path to the output pdf file (N.B. this function can also output PNG if specified in the filename extension) - (java expects a String)
	#' @param maxWidthInches what is the maximum allowable width? - (defaulting to 6.25) - (java expects a double)
	#' @param maxHeightInches what is the maximium allowable height? (if the content is larger than this then it will overflow to another page) - (defaulting to 9.75) - (java expects a double)
	#' @param formats If the outFile does not specify a file extension then you can do so here as "png" or "pdf" or both. - (defaulting to c('pdf','png')) - (java expects a RCharacterVector)
	#' @param pngDpi if outputting a PNG the dpi will determine the dimensions of the image. - (defaulting to 300) - (java expects a double)
	#' @return RCharacterVector: 
	#' the filename(s) written to (with extension '.pdf' and '.png' if outFile did not have an extension).
	fitIntoPage = function(htmlFragment, outFile, maxWidthInches=6.25, maxHeightInches=9.75, formats=c('pdf','png'), pngDpi=300) {
		# copy parameters
		tmp_htmlFragment = self$.api$.toJava$String(htmlFragment);
		tmp_outFile = self$.api$.toJava$String(outFile);
		tmp_maxWidthInches = self$.api$.toJava$double(maxWidthInches);
		tmp_maxHeightInches = self$.api$.toJava$double(maxHeightInches);
		tmp_formats = self$.api$.toJava$RCharacterVector(formats);
		tmp_pngDpi = self$.api$.toJava$double(pngDpi);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacterVector;", method="fitIntoPage" , tmp_htmlFragment, tmp_outFile, tmp_maxWidthInches, tmp_maxHeightInches, tmp_formats, tmp_pngDpi, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RCharacterVector(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' fitIntoA4: 
	#' Render HTML string to fit into an A4 page,
	#' @param htmlFragment a HTML fragment, e.g. the table element. It is usually expected there will not be any page media directives in the HTML - (java expects a String)
	#' @param outFile the full path to the output pdf file (N.B. this function can also output PNG if specified in the filename extension) - (java expects a String)
	#' @param xMarginInInches page margins - (defaulting to 1.0) - (java expects a double)
	#' @param yMarginInInches page margins - (defaulting to 1.0) - (java expects a double)
	#' @param formats If the outFile does not specify a file extension then you can do so here as "png" or "pdf" or both. - (defaulting to c('pdf','png')) - (java expects a RCharacterVector)
	#' @return RCharacterVector: 
	#' the filename(s) written to (with extension '.pdf' and '.png' if outFile did not have an extension).
	fitIntoA4 = function(htmlFragment, outFile, xMarginInInches=1.0, yMarginInInches=1.0, formats=c('pdf','png')) {
		# copy parameters
		tmp_htmlFragment = self$.api$.toJava$String(htmlFragment);
		tmp_outFile = self$.api$.toJava$String(outFile);
		tmp_xMarginInInches = self$.api$.toJava$double(xMarginInInches);
		tmp_yMarginInInches = self$.api$.toJava$double(yMarginInInches);
		tmp_formats = self$.api$.toJava$RCharacterVector(formats);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacterVector;", method="fitIntoA4" , tmp_htmlFragment, tmp_outFile, tmp_xMarginInInches, tmp_yMarginInInches, tmp_formats, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RCharacterVector(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	#' @description The output of toString() of this HtmlConverter
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this HtmlConverter
	#' @param object The R6 instance to test for equality to this HtmlConverter  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		if(!is.null(self$.jobj)) {
			.jcall(self$.jobj, returnSig = "V", method="close", check=FALSE)
			e = .jgetEx(clear=TRUE)
			if (!is.null(e)) {
				self$.api$.log$error(e$getMessage())
			}
			self$.api$printMessages() 
		}
		self$.jobj = .jnull("uk/co/terminological/html2pdfr/HtmlConverter")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
