# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rob.challen@bristol.ac.uk
# R Wrapper For Openhtmltopdf Java Library
#' R6 Bindings for Java HtmlConverter
#'
#' @description
#' missing description
#' 
#' This is a class of the html2pdfr generated R library.
#' 
#' Version: 0.4.0
#' 
#' Generated: 2022-07-05T15:48:04.468
#'
#' @details
	#' no details
#' @export
HtmlConverter = R6::R6Class("HtmlConverter", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new HtmlConverter this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new HtmlConverter object.
	#' @examples
	#' J = html2pdfr::JavaApi$get();
	#' instance = J$HtmlConverter$new(fontfiles)
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	
	#' @description The output of toString() of this HtmlConverter
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this HtmlConverter
	#' @param object The R6 instance to test for equality to this HtmlConverter  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		if(!is.null(self$.jobj)) {
			.jcall(self$.jobj, returnSig = "V", method="close", check=FALSE)
			e = .jgetEx(clear=TRUE)
			if (!is.null(e)) {
				self$.api$.log$error(e$getMessage())
			}
			self$.api$printMessages() 
		}
		self$.jobj = .jnull("uk/co/terminological/html2pdfr/HtmlConverter")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
